apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
  labels: 
    app: helloworld
  #namespace: python-test
spec:
  type: NodePort
  selector:
    app: helloworld
  ports: 
    - name: http
      port: 3000
      targetPort: 30000
  


